version: '3.6'

services:
 rabbitmq:
    container_name: rabbitmq-examples
    image: 'rabbitmq:3-management'
    ports:
      - 15672:15672
      - 5672:5672
    network_mode: host
    volumes:
      - ./db-data/rabbitmq/:/var/lib/rabbitmq/